#!/usr/bin/env bash
# Generated by TraceEnv — do not edit manually.
# Generated at: 2026-03-16T15:53:45.672Z

set -euo pipefail

# Prerequisites:
#   - Node.js v18+
#   - Docker

npm install
docker compose up -d
cp .env.example .env
npm run build

echo "Setup complete!"
