import * as fs from 'fs';
import * as path from 'path';
import { SynthesisResult } from '../ai/llm';

/**
 * Writes a `SETUP.md` file to `outputDir` with human-readable setup
 * instructions derived from the synthesis result.
 * Returns the absolute path of the written file.
 */
export function generateReadme(
  result: SynthesisResult,
  projectName: string,
  outputDir: string
): string {
  const outputPath = path.join(outputDir, 'SETUP.md');

  const lines: string[] = [
    `# ${projectName} — Setup`,
    '',
    '> Generated by [TraceEnv](https://github.com/Arjun-Walia/TraceEnv) — documentation from execution history.',
    '',
    '## Description',
    '',
    result.description,
    '',
  ];

  if (result.prerequisites.length > 0) {
    lines.push('## Prerequisites');
    lines.push('');
    result.prerequisites.forEach((p) => lines.push(`- ${p}`));
    lines.push('');
  }

  lines.push('## Setup');
  lines.push('');
  lines.push('Run the generated setup script:');
  lines.push('');
  lines.push('```bash');
  lines.push('bash setup.sh');
  lines.push('```');
  lines.push('');
  lines.push('Or run the steps manually:');
  lines.push('');
  lines.push('```bash');
  result.setupCommands.forEach((cmd) => lines.push(cmd));
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Generated at ${new Date().toISOString()} by TraceEnv*`);

  fs.writeFileSync(outputPath, lines.join('\n'));
  return outputPath;
}
