import * as fs from 'fs';
import * as path from 'path';
import { SynthesisResult } from '../ai/llm';

/**
 * Writes a `setup.sh` script to `outputDir` that reproduces the observed
 * environment. Returns the absolute path of the written file.
 */
export function generateSetupScript(
  result: SynthesisResult,
  outputDir: string
): string {
  const outputPath = path.join(outputDir, 'setup.sh');

  const lines: string[] = [
    '#!/usr/bin/env bash',
    '# Generated by TraceEnv - do not edit manually.',
    `# Generated at: ${new Date().toISOString()}`,
    '',
    'set -euo pipefail',
    '',
  ];

  if (result.prerequisites.length > 0) {
    lines.push('# Prerequisites:');
    result.prerequisites.forEach((p) => lines.push(`#   - ${p}`));
    lines.push('');
  }

  result.setupCommands.forEach((cmd) => lines.push(cmd));

  lines.push('');
  lines.push('echo "Setup complete!"');
  lines.push('');

  fs.writeFileSync(outputPath, lines.join('\n'), { mode: 0o755 });
  return outputPath;
}
